language: ruby
rvm: 2.6.5

services:
  - mysql

branches:
  only: 
    - master
    - test_code_create

install: bundle install

before_install:
  - mysql -e 'CREATE DATABASE invoice_board3_test;'

script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec