language: ruby
rvm:
  - rbx-3
rvm: 2.6.5

services:
  - mysql

bundler_args: --jobs=3 --retry=3
cache: bundler

branches:
  only: 
    - master
    - test_code_create

install: bundle install

before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE invoice_board3_test;'

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec