
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: invoice_board3_development


test:
  <<: *default
  database: invoice_board3_test
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock



production:
  <<: *default
  database: invoice_board3_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: i-database.c7r7ssbsom65.ap-northeast-1.rds.amazonaws.com